/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.AdminController;
import Model.Customer;
import javax.swing.JOptionPane;

/**
 *
 * @author longd
 */
public class AccountSetting extends javax.swing.JFrame {

    private Customer cus;
    /**
     * Creates new form AccountSetting
     */
    public AccountSetting(Customer cus) {
        this.cus= cus;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        detail = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lab_type1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        fullname = new javax.swing.JTextField();
        lab_cfname = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lab_type2 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lab_cfname1 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        date = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        lab_type4 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        phone = new javax.swing.JTextField();
        lab_cphone = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        bg_genre = new javax.swing.JPanel();
        lab_genre = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        genre_drama = new javax.swing.JCheckBox();
        genre_comedy = new javax.swing.JCheckBox();
        genre_action = new javax.swing.JCheckBox();
        footer = new javax.swing.JPanel();
        jBut_Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 350));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(64, 33, 100));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Account Setting");
        jLabel1.setPreferredSize(new java.awt.Dimension(138, 50));
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        detail.setBackground(new java.awt.Color(64, 33, 100));
        detail.setPreferredSize(new java.awt.Dimension(540, 200));
        detail.setLayout(new java.awt.GridLayout(5, 1, 10, 10));

        jPanel5.setBackground(new java.awt.Color(64, 33, 100));
        jPanel5.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel13.setBackground(new java.awt.Color(64, 33, 100));
        jPanel13.setPreferredSize(new java.awt.Dimension(165, 37));
        jPanel13.setLayout(new java.awt.BorderLayout(10, 10));

        lab_type1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type1.setForeground(new java.awt.Color(255, 255, 255));
        lab_type1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_type1.setText("Full Name");
        jPanel13.add(lab_type1, java.awt.BorderLayout.LINE_END);

        jPanel5.add(jPanel13, java.awt.BorderLayout.WEST);

        jPanel14.setBackground(new java.awt.Color(64, 33, 100));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        fullname.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel14.add(fullname);
        fullname.setText(cus.getFullname());

        lab_cfname.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel14.add(lab_cfname);

        jPanel5.add(jPanel14, java.awt.BorderLayout.CENTER);

        detail.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(64, 33, 100));
        jPanel6.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel15.setBackground(new java.awt.Color(64, 33, 100));
        jPanel15.setPreferredSize(new java.awt.Dimension(165, 37));
        jPanel15.setLayout(new java.awt.BorderLayout(10, 10));

        lab_type2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type2.setForeground(new java.awt.Color(255, 255, 255));
        lab_type2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_type2.setText("DOB");
        jPanel15.add(lab_type2, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel15, java.awt.BorderLayout.WEST);

        jPanel16.setBackground(new java.awt.Color(64, 33, 100));
        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lab_cfname1.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel16.add(lab_cfname1);

        year.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jPanel16.add(year);

        month.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel16.add(month);

        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jPanel16.add(date);

        jPanel6.add(jPanel16, java.awt.BorderLayout.CENTER);

        detail.add(jPanel6);

        jPanel8.setBackground(new java.awt.Color(64, 33, 100));
        jPanel8.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel19.setBackground(new java.awt.Color(64, 33, 100));
        jPanel19.setPreferredSize(new java.awt.Dimension(165, 37));
        jPanel19.setLayout(new java.awt.BorderLayout(10, 10));

        lab_type4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type4.setForeground(new java.awt.Color(255, 255, 255));
        lab_type4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_type4.setText("Phone");
        jPanel19.add(lab_type4, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel19, java.awt.BorderLayout.WEST);

        jPanel20.setBackground(new java.awt.Color(64, 33, 100));
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        phone.setPreferredSize(new java.awt.Dimension(300, 30));
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.setText(cus.getPhone());
        jPanel20.add(phone);

        lab_cphone.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel20.add(lab_cphone);

        jPanel8.add(jPanel20, java.awt.BorderLayout.CENTER);

        detail.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(64, 33, 100));
        jPanel9.setLayout(new java.awt.BorderLayout(20, 20));

        bg_genre.setBackground(new java.awt.Color(64, 33, 100));
        bg_genre.setPreferredSize(new java.awt.Dimension(165, 37));
        bg_genre.setLayout(new java.awt.BorderLayout(10, 10));

        lab_genre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_genre.setForeground(new java.awt.Color(255, 255, 255));
        lab_genre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_genre.setText("Favourite Genre");
        bg_genre.add(lab_genre, java.awt.BorderLayout.CENTER);

        jPanel9.add(bg_genre, java.awt.BorderLayout.WEST);

        jPanel22.setBackground(new java.awt.Color(64, 33, 100));
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        genre_drama.setBackground(new java.awt.Color(64, 33, 100));
        genre_drama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_drama.setForeground(new java.awt.Color(255, 255, 255));
        genre_drama.setSelected(true);
        genre_drama.setText("Drama");
        jPanel22.add(genre_drama);

        genre_comedy.setBackground(new java.awt.Color(64, 33, 100));
        genre_comedy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_comedy.setForeground(new java.awt.Color(255, 255, 255));
        genre_comedy.setSelected(true);
        genre_comedy.setText("Comedy");
        jPanel22.add(genre_comedy);

        genre_action.setBackground(new java.awt.Color(64, 33, 100));
        genre_action.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_action.setForeground(new java.awt.Color(255, 255, 255));
        genre_action.setSelected(true);
        genre_action.setText("Action");
        jPanel22.add(genre_action);
        if(cus.getFavouriteGenre().contains("Action"))
        genre_action.setSelected(true);

        jPanel9.add(jPanel22, java.awt.BorderLayout.CENTER);

        detail.add(jPanel9);

        jPanel1.add(detail, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(64, 33, 100));
        footer.setPreferredSize(new java.awt.Dimension(640, 50));

        jBut_Save.setBackground(new java.awt.Color(255, 255, 255));
        jBut_Save.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jBut_Save.setForeground(new java.awt.Color(64, 33, 100));
        jBut_Save.setText("Save");
        jBut_Save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut_Save.setBorderPainted(false);
        jBut_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBut_Save.setPreferredSize(new java.awt.Dimension(100, 29));
        jBut_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_SaveActionPerformed(evt);
            }
        });
        footer.add(jBut_Save);

        jPanel1.add(footer, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        // TODO add your handling code here:
        String key = phone.getText();
        if(key.length()>10){
            lab_cphone.setVisible(true);
            lab_cphone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png")));
            return;
        }

        for(int i = 0;i<key.length();i++){
            if(!(key.charAt(i)<='9' &&key.charAt(i)>='0')){
                lab_cphone.setVisible(true);
                lab_cphone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png")));
                return;
            }
        }
        lab_cphone.setVisible(false);
    }//GEN-LAST:event_phoneFocusLost

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void jBut_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_SaveActionPerformed
        // TODO add your handling code here:
        cus.setFullName(fullname.getText()); 
        //String pass = String.valueOf(password.getPassword());
        cus.setDoB( (String)year.getSelectedItem() + "/" + (String)month.getSelectedItem() + "/" + (String)date.getSelectedItem());
        
        cus.setPhone(phone.getText());

        String favgenre = "";
        if (genre_drama.isSelected())
        favgenre += genre_drama.getText() + ", ";
        if (genre_action.isSelected())
        favgenre += genre_action.getText() + ", ";
        if (genre_comedy.isSelected())
        favgenre += genre_comedy.getText() + ", ";
        if (favgenre.length() != 0){
            favgenre = favgenre.substring(0, favgenre.length() - 2);
            cus.setFavouriteGenre(favgenre);
            boolean check = AdminController.updateACustomer(cus);
            if(!check){
                JOptionPane.showMessageDialog(this, "Something went wrong", "Information", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Save setting succesfully", "Information", JOptionPane.INFORMATION_MESSAGE);

            }
        }

    }//GEN-LAST:event_jBut_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountSetting(new Customer(1,"2","3","4","5","6","7")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_genre;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JPanel detail;
    private javax.swing.JPanel footer;
    private javax.swing.JTextField fullname;
    private javax.swing.JCheckBox genre_action;
    private javax.swing.JCheckBox genre_comedy;
    private javax.swing.JCheckBox genre_drama;
    private javax.swing.JButton jBut_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lab_cfname;
    private javax.swing.JLabel lab_cfname1;
    private javax.swing.JLabel lab_cphone;
    private javax.swing.JLabel lab_genre;
    private javax.swing.JLabel lab_type1;
    private javax.swing.JLabel lab_type2;
    private javax.swing.JLabel lab_type4;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField phone;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
