/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Theater;
import Model.Film;
import DAO.FilmDAO;
import DAO.TheaterDAO;
import DAO.ShowtimeDAO;
import com.github.lgooddatepicker.components.DatePickerSettings;
import java.awt.Color;
import java.util.ArrayList;


/**
 *
 * @author nguye
 */
public class AddShowtimes extends javax.swing.JFrame {

    int mpX, mpY;
    ManageShowtimes parent;
    /**
     * Creates new form AddAnUser
     */
    //AddShowtimes parent =null;
    public AddShowtimes(ManageShowtimes parent) {
        this.parent = parent;
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_type = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        detail = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        cb_film = new javax.swing.JComboBox<>();
        ArrayList<Film> lstFilms = FilmDAO.getAllFilm();
        for(int i = 0; i<lstFilms.size();i++)             
        cb_film.addItem(lstFilms.get(i));
        jPanel31 = new javax.swing.JPanel();
        cb_theater = new javax.swing.JComboBox<>();
        ArrayList<Theater> lstTheaters = TheaterDAO.getAllTheaters();
        for(int i = 0; i<lstTheaters.size();i++)             
        cb_theater.addItem(lstTheaters.get(i));

        jPanel32 = new javax.swing.JPanel();
        cb_starttime = new javax.swing.JComboBox<>();
        for(int x = 8; x<= 22;x+=2){
            cb_starttime.addItem(Integer.toString(x)+":00:00");
        }
        jPanel26 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        daybegin = new com.github.lgooddatepicker.components.DatePicker();
        daybegin.setDateToToday();
        DatePickerSettings settings1 = daybegin.getSettings();
        settings1.setColor(DatePickerSettings.DateArea.BackgroundMonthAndYearNavigationButtons, new Color(64,33,100));
        settings1.setColor(DatePickerSettings.DateArea.TextCalendarPanelLabelsOnHover, new Color(64,33,100));
        settings1.setColor(DatePickerSettings.DateArea.TextMonthAndYearMenuLabels, new Color(64,33,100));
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dayend = new com.github.lgooddatepicker.components.DatePicker();
        dayend.setDateToToday();
        DatePickerSettings settings = dayend.getSettings();
        settings.setColor(DatePickerSettings.DateArea.BackgroundMonthAndYearNavigationButtons, new Color(64,33,100));
        settings.setColor(DatePickerSettings.DateArea.TextCalendarPanelLabelsOnHover, new Color(64,33,100));
        settings.setColor(DatePickerSettings.DateArea.TextMonthAndYearMenuLabels, new Color(64,33,100));
        jPanel27 = new javax.swing.JPanel();
        ignore = new javax.swing.JCheckBox();
        mess = new javax.swing.JLabel();

        lab_type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type.setForeground(new java.awt.Color(255, 255, 255));
        lab_type.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_type.setText("Type of Account");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(64, 33, 100));
        setMinimumSize(new java.awt.Dimension(575, 402));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(64, 33, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(64, 33, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btn_exit.setBackground(new java.awt.Color(64, 33, 100));
        btn_exit.setPreferredSize(new java.awt.Dimension(40, 30));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        btn_exit.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 30));
        btn_exit.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(btn_exit, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        main.setBackground(new java.awt.Color(64, 33, 100));
        main.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(64, 33, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(640, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD SHOWTIMES");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jLabel2, java.awt.BorderLayout.CENTER);

        main.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        footer.setBackground(new java.awt.Color(64, 33, 100));
        footer.setPreferredSize(new java.awt.Dimension(640, 50));

        save.setText("Save");
        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.setBorderPainted(false);
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        save.setForeground(new java.awt.Color(64, 33, 100));
        save.setPreferredSize(new java.awt.Dimension(100, 29));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        footer.add(save);

        main.add(footer, java.awt.BorderLayout.PAGE_END);

        detail.setBackground(new java.awt.Color(64, 33, 100));
        detail.setLayout(new java.awt.GridLayout(3, 1, 10, 10));

        jPanel21.setBackground(new java.awt.Color(64, 33, 100));
        jPanel21.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        jPanel28.setBackground(new java.awt.Color(64, 33, 100));
        jPanel28.setPreferredSize(new java.awt.Dimension(150, 84));

        cb_film.setPreferredSize(new java.awt.Dimension(170, 25));
        cb_film.setToolTipText("Film");
        jPanel28.add(cb_film);

        jPanel21.add(jPanel28);

        jPanel31.setBackground(new java.awt.Color(64, 33, 100));
        jPanel31.setPreferredSize(new java.awt.Dimension(150, 84));

        cb_theater.setPreferredSize(new java.awt.Dimension(170, 25));
        cb_theater.setToolTipText("Theater");
        jPanel31.add(cb_theater);

        jPanel21.add(jPanel31);

        jPanel32.setBackground(new java.awt.Color(64, 33, 100));
        jPanel32.setPreferredSize(new java.awt.Dimension(150, 84));

        cb_starttime.setPreferredSize(new java.awt.Dimension(170, 25));
        cb_starttime.setToolTipText("Starttime");
        jPanel32.add(cb_starttime);

        jPanel21.add(jPanel32);

        detail.add(jPanel21);

        jPanel26.setBackground(new java.awt.Color(64, 33, 100));
        jPanel26.setMinimumSize(new java.awt.Dimension(120, 30));
        jPanel26.setLayout(new java.awt.GridLayout(1, 4));

        jPanel5.setBackground(new java.awt.Color(64, 33, 100));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel3.setText("Begining Date");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jLabel3);

        daybegin.setMinimumSize(new java.awt.Dimension(150, 20));
        daybegin.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel5.add(daybegin);

        jPanel26.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(64, 33, 100));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("End Date");
        jPanel6.add(jLabel4);

        dayend.setMinimumSize(new java.awt.Dimension(150, 20));
        dayend.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel6.add(dayend);

        jPanel26.add(jPanel6);

        detail.add(jPanel26);

        jPanel27.setBackground(new java.awt.Color(64, 33, 100));
        jPanel27.setLayout(new java.awt.BorderLayout());

        ignore.setSelected(true);
        ignore.setText("Ignore showtimes whose start time is used");
        ignore.setBackground(new java.awt.Color(64, 33, 100));
        ignore.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ignore.setForeground(new java.awt.Color(255, 255, 255));
        ignore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ignore.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ignore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignoreActionPerformed(evt);
            }
        });
        jPanel27.add(ignore, java.awt.BorderLayout.PAGE_START);

        mess.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mess.setForeground(new java.awt.Color(204, 0, 51));
        mess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel27.add(mess, java.awt.BorderLayout.CENTER);

        detail.add(jPanel27);

        main.add(detail, java.awt.BorderLayout.CENTER);

        jPanel1.add(main, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(640, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        parent.getShowtimes();
        this.dispose();

    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        // TODO add your handling code here:(37,12,65)
        btn_exit.setBackground(Color.red);
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        // TODO add your handling code here:
        btn_exit.setBackground(new Color(64,33,100));

    }//GEN-LAST:event_btn_exitMouseExited

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        Film film = (Film)cb_film.getSelectedItem();
        Theater theater = (Theater)cb_theater.getSelectedItem();
        String starttime = (String)cb_starttime.getSelectedItem();
        if(daybegin.getDate()== null || dayend.getDate()==null){
            mess.setText("Please fill full information");
            return;
            
        }
        if(daybegin.getDate().compareTo(dayend.getDate())>0){
            mess.setText("The begining day and end day are invalid. Please choose them again! ");
            return;
        }
        int res = ShowtimeDAO.addShowtimes(film.getID(),theater.getID(), starttime, daybegin.toString(), dayend.toString(), ignore.isSelected());
        mess.setText("There are "+res+" showtimes added");
    }//GEN-LAST:event_saveActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        mpX = evt.getX();
        mpY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        setLocation(getLocation().x + evt.getX() - mpX,getLocation().y + evt.getY() - mpY );
        
    }//GEN-LAST:event_formMouseDragged

    private void ignoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ignoreActionPerformed
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddShowtimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddShowtimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddShowtimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddShowtimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddShowtimes().setVisible(true);
//            }
//        });
//    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_exit;
    private javax.swing.JComboBox<Film> cb_film;
    private javax.swing.JComboBox<String> cb_starttime;
    private javax.swing.JComboBox<Theater> cb_theater;
    private com.github.lgooddatepicker.components.DatePicker daybegin;
    private com.github.lgooddatepicker.components.DatePicker dayend;
    private javax.swing.JPanel detail;
    private javax.swing.JPanel footer;
    private javax.swing.JCheckBox ignore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lab_type;
    private javax.swing.JPanel main;
    private javax.swing.JLabel mess;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
