/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CustomerController;
import Model.Customer;
import Model.Film;
import Model.Showtime;
import Model.Theater;
import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.demo.FullDemo;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.util.ArrayList;

/**
 *
 * @author ngnth
 */
public class CustomerView extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    public CustomerView(Customer cus) {
        customer = cus;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void createListTheaterPanel (javax.swing.JPanel theaterListPanel,ArrayList<Theater> theaterlist){
        for (int i = 0; i < theaterlist.size(); i++){
            createTheaterPanel(theaterListPanel,theaterlist.get(i),i);
        }
    }
    private void createTheaterPanel(javax.swing.JPanel theaterListPanel, Theater theater, int pos){
        javax.swing.JLabel theaterlabel;
        javax.swing.JPanel theaterpanel;
        theaterpanel = new javax.swing.JPanel();
        theaterlabel = new javax.swing.JLabel();
        theaterpanel.setBackground(new java.awt.Color(199, 183, 158));
        theaterpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        theaterlabel.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        theaterlabel.setForeground(new java.awt.Color(255, 255, 255));
        theaterlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        theaterlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/woodenbg.jpg"))); // NOI18N
        theaterlabel.setText(theater.getName());
        theaterlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        theaterlabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        theaterlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                theaterlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout theaterpanelLayout = new javax.swing.GroupLayout(theaterpanel);
        theaterpanel.setLayout(theaterpanelLayout);
        theaterpanelLayout.setHorizontalGroup(
                theaterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(theaterpanelLayout.createSequentialGroup()
                                .addComponent(theaterlabel)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        theaterpanelLayout.setVerticalGroup(
                theaterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(theaterlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        int posX = 40 + 320*(pos%3);
        int posY = 40 + 120*(pos/3);
        theaterListPanel.add(theaterpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(posX, posY, -1, -1));
    }
    private void createListMoviePanel (javax.swing.JPanel movieListPanel, ArrayList<Film> filmlist){
        int len = 6;
        if (filmlist.size() < 6){
            len = filmlist.size();
        }
        for (int i = 0; i < 6; i++){
            addMoviePanel(movieListPanel, filmlist.get(i),i);
        }
    }
    private void addMoviePanel(javax.swing.JPanel movieListPanel, Film film, int pos){
        javax.swing.JPanel moviePanel;
        javax.swing.JLabel moviePoster;
        javax.swing.JLabel filmLabel;
        moviePanel = new javax.swing.JPanel();
        moviePoster = new javax.swing.JLabel();
        filmLabel = new javax.swing.JLabel();
        moviePanel.setBackground(new java.awt.Color(38, 19, 66));
        moviePoster.setIcon(new javax.swing.ImageIcon(getClass().getResource(film.getLinkimg()))); // NOI18N

        filmLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        filmLabel.setForeground(new java.awt.Color(255, 255, 255));
        filmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filmLabel.setText(film.getTitle());
        filmLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filmLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filmLabelMouseClicked(evt);
            }

            private void filmLabelMouseClicked(MouseEvent evt) {
            }
        });

        javax.swing.GroupLayout moviePanel2Layout = new javax.swing.GroupLayout(moviePanel);
        moviePanel.setLayout(moviePanel2Layout);
        moviePanel2Layout.setHorizontalGroup(
                moviePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(moviePanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(moviePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(moviePoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(filmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(49, Short.MAX_VALUE))
        );
        moviePanel2Layout.setVerticalGroup(
                moviePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(moviePanel2Layout.createSequentialGroup()
                                .addComponent(moviePoster)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addContainerGap())
        );
        int posX = 0 + 320*(pos%3);
        int posY = 40 + 410*(pos/3);
        movieListPanel.add(moviePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(posX, posY, -1, -1));
    }
    private javax.swing.JPanel createFilmPanel(Film film){
        javax.swing.JLabel cast;
        javax.swing.JLabel castLab;
        javax.swing.JLabel dateLab;
        DatePickerSettings dateSettings;
        DatePicker datePicker;
        javax.swing.JTextArea description;
        javax.swing.JLabel descriptionLab;
        javax.swing.JLabel director;
        javax.swing.JLabel directorLab;
        javax.swing.JLabel durationLab;
        javax.swing.JPanel filmInfoPanel;
        javax.swing.JPanel filmLab;
        javax.swing.JPanel filmPanel;
        javax.swing.JLabel filmTitle;
        javax.swing.JLabel genre;
        javax.swing.JLabel genreLab;
        javax.swing.JPanel leftSep;
        javax.swing.JLabel poster;
        javax.swing.JLabel releaseDate;
        javax.swing.JLabel releaseDateLab;
        javax.swing.JPanel rightSep;
        javax.swing.JLabel showingtimeLabel;
        javax.swing.JPanel showtimePanel;
        javax.swing.JLabel showtimeSelection;
        javax.swing.JLabel time;
        dateSettings = new DatePickerSettings();
        filmPanel = new javax.swing.JPanel();
        filmLab = new javax.swing.JPanel();
        filmTitle = new javax.swing.JLabel();
        rightSep = new javax.swing.JPanel();
        leftSep = new javax.swing.JPanel();
        filmInfoPanel = new javax.swing.JPanel();
        poster = new javax.swing.JLabel();
        directorLab = new javax.swing.JLabel();
        director = new javax.swing.JLabel();
        castLab = new javax.swing.JLabel();
        genreLab = new javax.swing.JLabel();
        genre = new javax.swing.JLabel();
        releaseDateLab = new javax.swing.JLabel();
        releaseDate = new javax.swing.JLabel();
        durationLab = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        descriptionLab = new javax.swing.JLabel();
        cast = new javax.swing.JLabel();
        description = new javax.swing.JTextArea();
        datePicker = new DatePicker(dateSettings);
        dateLab = new javax.swing.JLabel();
        showtimePanel = new javax.swing.JPanel();
        showtimeSelection = new javax.swing.JLabel();
        showingtimeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicketBox");

        filmPanel.setBackground(new java.awt.Color(38, 19, 66));
        filmPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filmLab.setBackground(new java.awt.Color(38, 19, 66));
        filmLab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filmTitle.setText("SAI GON IN THE RAIN");
        filmTitle.setBackground(new java.awt.Color(0, 0, 51));
        filmTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        filmTitle.setForeground(new java.awt.Color(255, 255, 255));
        filmLab.add(filmTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 309, -1));

        javax.swing.GroupLayout rightSepLayout = new javax.swing.GroupLayout(rightSep);
        rightSep.setLayout(rightSepLayout);
        rightSepLayout.setHorizontalGroup(
                rightSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
        rightSepLayout.setVerticalGroup(
                rightSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 5, Short.MAX_VALUE)
        );

        filmLab.add(rightSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 300, 5));

        javax.swing.GroupLayout leftSepLayout = new javax.swing.GroupLayout(leftSep);
        leftSep.setLayout(leftSepLayout);
        leftSepLayout.setHorizontalGroup(
                leftSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
        leftSepLayout.setVerticalGroup(
                leftSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 5, Short.MAX_VALUE)
        );

        filmLab.add(leftSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, 5));

        filmPanel.add(filmLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 950, 40));

        filmInfoPanel.setBackground(new java.awt.Color(38, 19, 66));

        poster.setIcon(new javax.swing.ImageIcon(getClass().getResource(film.getLinkimg()))); // NOI18N

        directorLab.setText("Director: ");
        directorLab.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        directorLab.setForeground(new java.awt.Color(255, 255, 255));

        director.setText(film.getDirector());
        director.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        director.setForeground(new java.awt.Color(255, 255, 255));

        castLab.setText("Cast:");
        castLab.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        castLab.setForeground(new java.awt.Color(255, 255, 255));

        genreLab.setText("Genre:");
        genreLab.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        genreLab.setForeground(new java.awt.Color(255, 255, 255));

        genre.setText(film.getGenre());
        genre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        genre.setForeground(new java.awt.Color(255, 255, 255));

        releaseDateLab.setText("Release Date:");
        releaseDateLab.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        releaseDateLab.setForeground(new java.awt.Color(255, 255, 255));

        releaseDate.setText(film.getReleasedDate());
        releaseDate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        releaseDate.setForeground(new java.awt.Color(255, 255, 255));

        durationLab.setText("Duration:");
        durationLab.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        durationLab.setForeground(new java.awt.Color(255, 255, 255));

        time.setText(Integer.toString(film.getDuration()));
        time.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));

        descriptionLab.setText("Description:");
        descriptionLab.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        descriptionLab.setForeground(new java.awt.Color(255, 255, 255));

        cast.setText(film.getCast());
        cast.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        cast.setForeground(new java.awt.Color(255, 255, 255));

        description.setColumns(20);
        description.setEditable(false);
        description.setLineWrap(true);
        description.setRows(5);
        description.setText(film.getDescription());
        description.setWrapStyleWord(true);
        description.setAutoscrolls(false);
        description.setBackground(new java.awt.Color(38, 19, 66));
        description.setBorder(null);
        description.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout filmInfoPanelLayout = new javax.swing.GroupLayout(filmInfoPanel);
        filmInfoPanel.setLayout(filmInfoPanelLayout);
        filmInfoPanelLayout.setHorizontalGroup(
                filmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(filmInfoPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(poster)
                                .addGap(43, 43, 43)
                                .addGroup(filmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(filmInfoPanelLayout.createSequentialGroup()
                                                .addComponent(directorLab, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(director, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(34, 34, 34))
                                        .addGroup(filmInfoPanelLayout.createSequentialGroup()
                                                .addComponent(genreLab, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(genre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(filmInfoPanelLayout.createSequentialGroup()
                                                .addComponent(durationLab, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(filmInfoPanelLayout.createSequentialGroup()
                                                .addComponent(releaseDateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(releaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(filmInfoPanelLayout.createSequentialGroup()
                                                .addGroup(filmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(filmInfoPanelLayout.createSequentialGroup()
                                                                .addComponent(castLab, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(descriptionLab, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        filmInfoPanelLayout.setVerticalGroup(
                filmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(filmInfoPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(filmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(directorLab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(director, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(filmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(castLab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cast, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(filmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(genreLab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(genre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(filmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(durationLab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(filmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(releaseDateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(releaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptionLab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filmInfoPanelLayout.createSequentialGroup()
                                .addContainerGap(86, Short.MAX_VALUE)
                                .addComponent(poster)
                                .addGap(49, 49, 49))
        );

        filmPanel.add(filmInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 890, 470));

        datePicker.setText("Pick a date");
        datePicker.setBackground(new java.awt.Color(38, 19, 66));
        filmPanel.add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        dateLab.setText("Dates");
        dateLab.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dateLab.setForeground(new java.awt.Color(255, 255, 255));
        filmPanel.add(dateLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 230, 40));

        showtimePanel.setBackground(new java.awt.Color(38, 19, 66));
        showtimePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showtimeSelection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticketbg.png"))); // NOI18N
        showtimeSelection.setText("18:00");
        showtimeSelection.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        showtimeSelection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showtimePanel.add(showtimeSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 117, -1));

        showingtimeLabel.setText("Dates");
        showingtimeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        showingtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        showtimePanel.add(showingtimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 230, 40));

        filmPanel.add(showtimePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 680, 890, 260));
        return filmPanel;
    }
    private javax.swing.JPanel createAccountPanel(){
        JPanel jPanel2 = new javax.swing.JPanel();
        JPanel mainPanel = new javax.swing.JPanel();
        JLabel accountSettingLabel = new javax.swing.JLabel();
        JPanel detail = new javax.swing.JPanel();
        JPanel fullnamePanel = new javax.swing.JPanel();
        JPanel fullnameLabelPanel = new javax.swing.JPanel();
        JLabel fullnameLabel = new javax.swing.JLabel();
        JPanel fullnameTextPanel = new javax.swing.JPanel();
        JTextField fullname = new javax.swing.JTextField();
        JLabel lab_cfname = new javax.swing.JLabel();
        JPanel passwordPanel = new javax.swing.JPanel();
        JPanel passwordLabelPanel = new javax.swing.JPanel();
        JLabel passwordLabel = new javax.swing.JLabel();
        JPanel passwordTextPanel = new javax.swing.JPanel();
        JPasswordField jPasswordField1 = new javax.swing.JPasswordField();
        JLabel lab_cphone1 = new javax.swing.JLabel();
        JPanel dobPanel = new javax.swing.JPanel();
        JPanel dobLabelPanel = new javax.swing.JPanel();
        JLabel dobLabel = new javax.swing.JLabel();
        JPanel  dobInputPanel = new javax.swing.JPanel();
        JComboBox year = new javax.swing.JComboBox<>();
        JComboBox month = new javax.swing.JComboBox<>();
        JComboBox  date = new javax.swing.JComboBox<>();
        JLabel lab_cfname1 = new javax.swing.JLabel();
        JPanel phonePanel = new javax.swing.JPanel();
        JPanel phoneLabelPanel = new javax.swing.JPanel();
        JLabel phoneLabel = new javax.swing.JLabel();
        JPanel phoneTextPanel = new javax.swing.JPanel();
        JTextField phone = new javax.swing.JTextField();
        JLabel lab_cphone = new javax.swing.JLabel();
        JPanel genrePanel = new javax.swing.JPanel();
        JPanel bg_genre = new javax.swing.JPanel();
        JLabel lab_genre = new javax.swing.JLabel();
        JPanel jPanel22 = new javax.swing.JPanel();
        JCheckBox genre_drama = new javax.swing.JCheckBox();
        JCheckBox genre_comedy = new javax.swing.JCheckBox();
        JCheckBox genre_action = new javax.swing.JCheckBox();
        JPanel footer = new javax.swing.JPanel();
        JButton jBut_Save = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 700));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        mainPanel.setBackground(new java.awt.Color(64, 33, 100));
        mainPanel.setLayout(new java.awt.BorderLayout());

        accountSettingLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accountSettingLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountSettingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountSettingLabel.setText("Account Setting");
        accountSettingLabel.setPreferredSize(new java.awt.Dimension(138, 50));
        mainPanel.add(accountSettingLabel, java.awt.BorderLayout.PAGE_START);

        detail.setBackground(new java.awt.Color(64, 33, 100));
        detail.setPreferredSize(new java.awt.Dimension(540, 200));
        detail.setLayout(new java.awt.GridLayout(6, 1, 5, 5));

        fullnamePanel.setBackground(new java.awt.Color(64, 33, 100));
        fullnamePanel.setLayout(new java.awt.BorderLayout(20, 20));

        fullnameLabelPanel.setBackground(new java.awt.Color(64, 33, 100));
        fullnameLabelPanel.setPreferredSize(new java.awt.Dimension(165, 37));
        fullnameLabelPanel.setLayout(null);

        fullnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fullnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        fullnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fullnameLabel.setText("Full Name");
        fullnameLabelPanel.add(fullnameLabel);
        fullnameLabel.setBounds(83, 0, 80, 42);

        fullnamePanel.add(fullnameLabelPanel, java.awt.BorderLayout.WEST);

        fullnameTextPanel.setBackground(new java.awt.Color(64, 33, 100));
        fullnameTextPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        fullname.setPreferredSize(new java.awt.Dimension(300, 30));
        fullnameTextPanel.add(fullname);
//        fullname.setText(cus.getFullname());

        lab_cfname.setPreferredSize(new java.awt.Dimension(40, 30));
        fullnameTextPanel.add(lab_cfname);

        fullnamePanel.add(fullnameTextPanel, java.awt.BorderLayout.CENTER);

        detail.add(fullnamePanel);

        passwordPanel.setBackground(new java.awt.Color(64, 33, 100));
        passwordPanel.setLayout(new java.awt.BorderLayout(20, 20));

        passwordLabelPanel.setBackground(new java.awt.Color(64, 33, 100));
        passwordLabelPanel.setPreferredSize(new java.awt.Dimension(165, 37));
        passwordLabelPanel.setLayout(null);

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordLabel.setText("Password");
        passwordLabelPanel.add(passwordLabel);
        passwordLabel.setBounds(0, 0, 165, 42);

        passwordPanel.add(passwordLabelPanel, java.awt.BorderLayout.WEST);

        passwordTextPanel.setBackground(new java.awt.Color(64, 33, 100));
        passwordTextPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPasswordField1.setPreferredSize(new java.awt.Dimension(300, 30));

        passwordTextPanel.add(jPasswordField1);

        lab_cphone1.setPreferredSize(new java.awt.Dimension(40, 30));
        passwordTextPanel.add(lab_cphone1);

        passwordPanel.add(passwordTextPanel, java.awt.BorderLayout.CENTER);

        detail.add(passwordPanel);

        dobPanel.setBackground(new java.awt.Color(64, 33, 100));
        dobPanel.setLayout(new java.awt.BorderLayout(20, 20));

        dobLabelPanel.setBackground(new java.awt.Color(64, 33, 100));
        dobLabelPanel.setPreferredSize(new java.awt.Dimension(165, 37));
        dobLabelPanel.setLayout(null);

        dobLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(255, 255, 255));
        dobLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dobLabel.setText("DOB");
        dobLabelPanel.add(dobLabel);
        dobLabel.setBounds(0, 0, 165, 42);

        dobPanel.add(dobLabelPanel, java.awt.BorderLayout.WEST);

        dobInputPanel.setBackground(new java.awt.Color(64, 33, 100));
        dobInputPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        year.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        dobInputPanel.add(year);

        month.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        dobInputPanel.add(month);

        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        dobInputPanel.add(date);

        lab_cfname1.setPreferredSize(new java.awt.Dimension(40, 30));
        dobInputPanel.add(lab_cfname1);

        dobPanel.add(dobInputPanel, java.awt.BorderLayout.CENTER);

        detail.add(dobPanel);

        phonePanel.setBackground(new java.awt.Color(64, 33, 100));
        phonePanel.setLayout(new java.awt.BorderLayout(20, 20));

        phoneLabelPanel.setBackground(new java.awt.Color(64, 33, 100));
        phoneLabelPanel.setPreferredSize(new java.awt.Dimension(165, 37));
        phoneLabelPanel.setLayout(null);

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phoneLabel.setText("Phone");
        phoneLabelPanel.add(phoneLabel);
        phoneLabel.setBounds(0, 0, 165, 42);

        phonePanel.add(phoneLabelPanel, java.awt.BorderLayout.WEST);

        phoneTextPanel.setBackground(new java.awt.Color(64, 33, 100));
        phoneTextPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        phone.setPreferredSize(new java.awt.Dimension(300, 30));

//        phone.setText(cus.getPhone());
        phoneTextPanel.add(phone);

        lab_cphone.setPreferredSize(new java.awt.Dimension(40, 30));
        phoneTextPanel.add(lab_cphone);

        phonePanel.add(phoneTextPanel, java.awt.BorderLayout.CENTER);

        detail.add(phonePanel);

        genrePanel.setBackground(new java.awt.Color(64, 33, 100));
        genrePanel.setLayout(new java.awt.BorderLayout(20, 20));

        bg_genre.setBackground(new java.awt.Color(64, 33, 100));
        bg_genre.setPreferredSize(new java.awt.Dimension(165, 37));
        bg_genre.setLayout(null);

        lab_genre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_genre.setForeground(new java.awt.Color(255, 255, 255));
        lab_genre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_genre.setText("Favourite Genre");
        bg_genre.add(lab_genre);
        lab_genre.setBounds(0, 0, 165, 42);

        genrePanel.add(bg_genre, java.awt.BorderLayout.WEST);

        jPanel22.setBackground(new java.awt.Color(64, 33, 100));
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        genre_drama.setBackground(new java.awt.Color(64, 33, 100));
        genre_drama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_drama.setForeground(new java.awt.Color(255, 255, 255));
        genre_drama.setSelected(true);
        genre_drama.setText("Drama");
        jPanel22.add(genre_drama);

        genre_comedy.setBackground(new java.awt.Color(64, 33, 100));
        genre_comedy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_comedy.setForeground(new java.awt.Color(255, 255, 255));
        genre_comedy.setSelected(true);
        genre_comedy.setText("Comedy");
        jPanel22.add(genre_comedy);

        genre_action.setBackground(new java.awt.Color(64, 33, 100));
        genre_action.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_action.setForeground(new java.awt.Color(255, 255, 255));
        genre_action.setSelected(true);
        genre_action.setText("Action");
        jPanel22.add(genre_action);
//        if(cus.getFavouriteGenre().contains("Action"))
        genre_action.setSelected(true);

        genrePanel.add(jPanel22, java.awt.BorderLayout.CENTER);

        detail.add(genrePanel);

        mainPanel.add(detail, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(64, 33, 100));
        footer.setPreferredSize(new java.awt.Dimension(640, 50));

        jBut_Save.setBackground(new java.awt.Color(255, 255, 255));
        jBut_Save.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jBut_Save.setForeground(new java.awt.Color(64, 33, 100));
        jBut_Save.setText("Save");
        jBut_Save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut_Save.setBorderPainted(false);
        jBut_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBut_Save.setPreferredSize(new java.awt.Dimension(100, 29));
        jBut_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBut_SaveActionPerformed(evt);
            }
        });
        footer.add(jBut_Save);

        mainPanel.add(footer, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(mainPanel);

        return jPanel2;
    }
    private javax.swing.JPanel createBookingPanel(){
        javax.swing.JPanel bookingpanel = new javax.swing.JPanel();
        javax.swing.JLabel movieLable;
        javax.swing.JComboBox<String> movieSelection;
        javax.swing.JLabel poster;
        javax.swing.JLabel showtimeSelection;
        javax.swing.JPanel sidepane;
        javax.swing.JLabel theaterLabel;
        javax.swing.JComboBox<String> theaterSelection;
        javax.swing.JPanel BookTicketLab;
        javax.swing.JLabel BookTicketText;
        javax.swing.JPanel leftSep;
        javax.swing.JPanel rightSep;
        javax.swing.JPanel showtimePanel;
        javax.swing.JButton btn_showshowtime;
        javax.swing.JLabel dateLabel;
        DatePickerSettings dateSettings;
        DatePicker datePicker;
        theaterSelection = new javax.swing.JComboBox<>();
        movieSelection = new javax.swing.JComboBox<>();
        theaterLabel = new javax.swing.JLabel();
        movieLable = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        dateSettings = new DatePickerSettings();
        dateSettings.setColor(DatePickerSettings.DateArea.CalendarBackgroundNormalDates, Color.CYAN);
        dateSettings.setColor(DatePickerSettings.DateArea.TextFieldBackgroundValidDate, Color.LIGHT_GRAY);
        dateSettings.setFontValidDate(new Font("Segoe UI", 0, 18));
        datePicker = new DatePicker(dateSettings);
        datePicker.setDateToToday();
        URL dateImageURL = FullDemo.class.getResource("/images/datepickerbutton1.png");
        Image dateExampleImage = Toolkit.getDefaultToolkit().getImage(dateImageURL);
        ImageIcon dateExampleIcon = new ImageIcon(dateExampleImage);
        JButton datePickerButton = datePicker.getComponentToggleCalendarButton();
        datePickerButton.setText("");
        datePickerButton.setIcon(dateExampleIcon);
        BookTicketLab = new javax.swing.JPanel();
        BookTicketText = new javax.swing.JLabel();
        rightSep = new javax.swing.JPanel();
        leftSep = new javax.swing.JPanel();
        showtimePanel = new javax.swing.JPanel();
        btn_showshowtime = new javax.swing.JButton();
        bookingpanel.setBackground(new java.awt.Color(38, 19, 66));
        bookingpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BookTicketLab.setBackground(new java.awt.Color(38, 19, 66));
        BookTicketLab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BookTicketText.setBackground(new java.awt.Color(0, 0, 51));
        BookTicketText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BookTicketText.setForeground(new java.awt.Color(255, 255, 255));
        BookTicketText.setText("BOOKING TICKET");
        BookTicketLab.add(BookTicketText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 309, -1));

        javax.swing.GroupLayout rightSepLayout = new javax.swing.GroupLayout(rightSep);
        rightSep.setLayout(rightSepLayout);
        rightSepLayout.setHorizontalGroup(
                rightSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
        rightSepLayout.setVerticalGroup(
                rightSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 5, Short.MAX_VALUE)
        );

        BookTicketLab.add(rightSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 300, 5));

        javax.swing.GroupLayout leftSepLayout = new javax.swing.GroupLayout(leftSep);
        leftSep.setLayout(leftSepLayout);
        leftSepLayout.setHorizontalGroup(
                leftSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
        leftSepLayout.setVerticalGroup(
                leftSepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 5, Short.MAX_VALUE)
        );

        BookTicketLab.add(leftSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, 5));

        bookingpanel.add(BookTicketLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 950, 40));

        theaterSelection.setBackground(new java.awt.Color(64, 33, 100));
        theaterSelection.setFont(new java.awt.Font("Segoe UI", 0, 18));
        theaterSelection.setForeground(new java.awt.Color(255, 255, 255));
        String[] theaternamelist = getTheaterNameList();
        theaterSelection.setModel(new javax.swing.DefaultComboBoxModel<>(theaternamelist));
        bookingpanel.add(theaterSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 280, 40));

        movieSelection.setBackground(new java.awt.Color(64, 33, 100));
        movieSelection.setFont(new java.awt.Font("Segoe UI", 0, 18));
        theaterSelection.setForeground(new java.awt.Color(255, 255, 255));
        String[] movienamelist = getFilmNameList();
        movieSelection.setModel(new javax.swing.DefaultComboBoxModel<>(movienamelist));
        bookingpanel.add(movieSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 260, 40));

        theaterLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        theaterLabel.setForeground(new java.awt.Color(255, 255, 255));
        theaterLabel.setText("THEATER");
        bookingpanel.add(theaterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 160, 40));

        movieLable.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        movieLable.setForeground(new java.awt.Color(255, 255, 255));
        movieLable.setText("MOVIE");
        bookingpanel.add(movieLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 160, 40));
        dateLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("DATE");
        bookingpanel.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 160, 40));
        datePicker.setBackground(new java.awt.Color(64, 33, 100));
        datePicker.setForeground(new java.awt.Color(255, 255, 255));
        bookingpanel.add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 260, 40));

        showtimePanel.setBackground(new java.awt.Color(38, 19, 66));
        showtimePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bookingpanel.add(showtimePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 780, 320));

        btn_showshowtime.setBackground(new java.awt.Color(126, 87, 194));
        btn_showshowtime.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btn_showshowtime.setForeground(new java.awt.Color(255, 255, 255));
        btn_showshowtime.setText("SHOW SHOWTIME");
        btn_showshowtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showshowtimeActionPerformed(evt, showtimePanel,movieSelection,theaterSelection, datePicker);
            }
        });
        bookingpanel.add(btn_showshowtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 190, 60));
        showtimePanel.setVisible(false);
        return bookingpanel;
    }

    private void btn_showshowtimeActionPerformed(java.awt.event.ActionEvent evt, javax.swing.JPanel showtimePanel,javax.swing.JComboBox<String> movieSelection, javax.swing.JComboBox<String> theaterSelection, DatePicker datePicker) {
        // TODO add your handling code here:
        showtimePanel.removeAll();
        showtimePanel.revalidate();
        showtimePanel.repaint();
        String film = (String) movieSelection.getSelectedItem();
        String theater = (String) theaterSelection.getSelectedItem();
        String date = datePicker.getDateStringOrEmptyString();
        createShowTimeLists(showtimePanel,film,theater,date);
        showtimePanel.setVisible(true);
    }
    void createShowTimeLists(javax.swing.JPanel showtimePanel, String film, String theater, String date){
        if (date == ""){
            javax.swing.JLabel noDate = new javax.swing.JLabel();
            noDate.setText("Please Pick A Date");
            noDate.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
            noDate.setForeground(new java.awt.Color(255, 0, 0));
            showtimePanel.add(noDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 0, 300, 40));
            return;
        }
        javax.swing.JLabel showingtimeLabel = new javax.swing.JLabel();
        showingtimeLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        showingtimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        showingtimeLabel.setText("SHOWING TIME");
        showtimePanel.add(showingtimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 230, 40));
        ArrayList<Showtime> showtimes = CustomerController.getAllShowtimesBy(theater,film, date);
        if (showtimes.size() == 0){
            javax.swing.JLabel noShowtime = new javax.swing.JLabel();
            noShowtime.setText("No Showtime On This Day");
            noShowtime.setFont(new java.awt.Font("Segoe UI Semibold", 2, 24)); // NOI18N
            noShowtime.setForeground(new java.awt.Color(255, 255, 255));
            showtimePanel.add(noShowtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 300, 40));
            return;
        }
        for (int i = 0; i < showtimes.size(); i ++){
            createShowTimeItems(showtimePanel,showtimes.get(i),i);
        }
    }
    void createShowTimeItems(javax.swing.JPanel showtimePanel, Showtime showtime, int pos){
        javax.swing.JLabel showtimeSelection;
        showtimeSelection = new javax.swing.JLabel();
        showtimeSelection.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        showtimeSelection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticketbg.png"))); // NOI18N
        showtimeSelection.setText(showtime.getStartTime().substring(0,5));
        showtimeSelection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showtimeSelection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showtimeSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showtimeSelectionMouseClicked(evt);
            }

            private void showtimeSelectionMouseClicked(MouseEvent evt) {

            }
        });
        int posX = 30 + (pos%4)*200;
        int posY = 90 + (pos/4)*80;
        showtimePanel.add(showtimeSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(posX, posY, 117, -1));

    }
    String[] getFilmNameList(){
        ArrayList<Film> fi = CustomerController.getAllFilms();
        String[] lst = new String[fi.size()];
        for (int i = 0; i < fi.size(); i++){
            lst[i] = fi.get(i).getTitle();
        }
        return lst;
    }
    String[] getTheaterNameList(){
        ArrayList<Theater> th = CustomerController.getAllTheaters();
                String[] lst = new String[th.size()];
        for (int i = 0; i < th.size(); i++){
            lst[i] = th.get(i).getName();
        }
        return lst;
    }
//    private javax.swing.JPanel createSeatsPanel(Showtime showtime){
//        JPanel seatspanel;
//        JPanel BookTicketLab;
//        JLabel BookTicketText;
//        JLabel Price;
//        JLabel btn_Back;
//        JButton btn_Book;
//    }
    private void initComponents() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("TicketBox");
        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        mainscrollpane = new javax.swing.JScrollPane();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpanel = createHomepanel();
        bookingpanel = createBookingPanel();
        personalpanel = createAccountPanel();
        sidepane = createSidepanel();

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 332, 700));

        mainscrollpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
//        mainscrollpane.getHorizontalScrollBar().setBackground(new java.awt.Color(38, 19, 66));
        mainscrollpane.setViewportView(mainpanel);
        bg.add(mainscrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 960, 700));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(647, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>
    private javax.swing.JPanel createSidepanel(){
        javax.swing.JPanel sidepane = new javax.swing.JPanel();
        javax.swing.JLabel homeLable;
        javax.swing.JLabel bookticketLogo;
        javax.swing.JLabel bookticketLabel;
        javax.swing.JLabel applogo;
        javax.swing.JLabel manageaccountLogo;
        javax.swing.JLabel manageaccountLabel;
        javax.swing.JPanel btn_home;
        javax.swing.JPanel btn_bookticket;
        javax.swing.JPanel btn_manageaccount;
        javax.swing.JLabel homeLogo;
        javax.swing.JLabel helloLab;
        javax.swing.JLabel logoutLab;
        javax.swing.JPanel infoPanel;
        javax.swing.JPanel btn_logout;
        helloLab = new javax.swing.JLabel();
        btn_logout = new javax.swing.JPanel();
        logoutLab = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_home = new javax.swing.JPanel();
        homeLogo = new javax.swing.JLabel();
        homeLable = new javax.swing.JLabel();
        btn_bookticket = new javax.swing.JPanel();
        bookticketLogo = new javax.swing.JLabel();
        bookticketLabel = new javax.swing.JLabel();
        btn_manageaccount = new javax.swing.JPanel();
        manageaccountLogo = new javax.swing.JLabel();
        manageaccountLabel = new javax.swing.JLabel();
        applogo = new javax.swing.JLabel();
        javax.swing.JPanel[] btns = {btn_home,btn_bookticket,btn_manageaccount};
        btn_home.setBackground(new java.awt.Color(85, 65, 118));
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMouseClicked(evt,btn_home,btns,0,mainpanel);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt,btn_home);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt,btn_home,home_onclick);
            }
        });
        btn_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeLogo.setForeground(new java.awt.Color(255, 255, 255));
        homeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_32px.png"))); // NOI18N
        btn_home.add(homeLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 16, -1, 42));

        homeLable.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        homeLable.setForeground(new java.awt.Color(255, 255, 255));
        homeLable.setText("Home");
        btn_home.add(homeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 16, 120, 42));

        sidepane.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 350, 70));

        btn_bookticket.setBackground(new java.awt.Color(64,33,100));
        btn_bookticket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_bookticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMouseClicked(evt,btn_bookticket, btns, 1,bookingpanel);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt,btn_bookticket);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt,btn_bookticket,bookticket_onclick);
            }
        });
        btn_bookticket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookticketLogo.setForeground(new java.awt.Color(255, 255, 255));
        bookticketLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bookticket.png"))); // NOI18N
        btn_bookticket.add(bookticketLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 16, -1, 42));

        bookticketLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        bookticketLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookticketLabel.setText("Book Ticket");
        btn_bookticket.add(bookticketLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 16, 120, 42));

        sidepane.add(btn_bookticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 360, 70));

        btn_manageaccount.setBackground(new java.awt.Color(64,33,100));
        btn_manageaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_manageaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMouseClicked(evt,btn_manageaccount,btns,2,personalpanel);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt,btn_manageaccount);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt,btn_manageaccount,personal_onclick);
            }
        });
        btn_manageaccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageaccountLogo.setForeground(new java.awt.Color(255, 255, 255));
        manageaccountLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/infologo.png"))); // NOI18N
        btn_manageaccount.add(manageaccountLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 16, -1, 42));

        manageaccountLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        manageaccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        manageaccountLabel.setText("Manage Account");
        btn_manageaccount.add(manageaccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 16, 171, 42));

        sidepane.add(btn_manageaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 360, 70));

        infoPanel.setBackground(new java.awt.Color(72, 19, 128));
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helloLab.setFont(new java.awt.Font("Segoe Script", 1, 22)); // NOI18N
        helloLab.setForeground(new java.awt.Color(255, 255, 255));
        helloLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        String[] name = customer.getFullname().split(" ");
        helloLab.setText("Hello " + name[name.length - 1]);
        infoPanel.add(helloLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 70));

        btn_logout.setBackground(new java.awt.Color(127, 120, 210));
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });

        logoutLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutdown.png"))); // NOI18N

        javax.swing.GroupLayout btn_logoutLayout = new javax.swing.GroupLayout(btn_logout);
        btn_logout.setLayout(btn_logoutLayout);
        btn_logoutLayout.setHorizontalGroup(
                btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logoutLab, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        btn_logoutLayout.setVerticalGroup(
                btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logoutLab, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        infoPanel.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 70, 70));

        sidepane.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 330, 70));
        applogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        sidepane.add(applogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));
        return sidepane;
    }

    private void btn_logoutMouseClicked(MouseEvent evt) {
        customer = null;
        this.dispose();
        new SignInView().setVisible(true);
    }

    private void btnMouseEntered(java.awt.event.MouseEvent evt, javax.swing.JPanel btn) {
        // TODO add your handling code here:
        btn.setBackground(new java.awt.Color(101, 84, 176));
    }

    private void btnMouseExited(java.awt.event.MouseEvent evt, javax.swing.JPanel btn, Boolean checkonclick) {
        // TODO add your handling code here:
        if (checkonclick){
            btn.setBackground(new java.awt.Color(85,65,118));
        }
        else
            btn.setBackground(new java.awt.Color(64,33,100));
    }

    private void btnMouseClicked(java.awt.event.MouseEvent evt, javax.swing.JPanel btn_click, javax.swing.JPanel[] btns, int clickstatus, javax.swing.JPanel choosepane) {
        // TODO add your handling code here:
        mainscrollpane.setViewportView(choosepane);
        for (int i =0; i < btns.length; i++){
            btns[i].setBackground(new java.awt.Color(64,33,100));
        }
        btn_click.setBackground(new java.awt.Color(85,65,118));
        home_onclick = false;
        bookticket_onclick = false;
        personal_onclick = false;
        switch (clickstatus){
            case 0:
                home_onclick = true;
                break;
            case 1:
                bookticket_onclick = true;
                break;
            case 2:
                personal_onclick = true;
                break;
        }
    }

    private void theaterlabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }
    private javax.swing.JPanel createHomepanel(){
        javax.swing.JPanel mainpanel;
        javax.swing.JLabel poster;
        javax.swing.JPanel movieListPanel;
        javax.swing.JPanel theaterLab;
        javax.swing.JPanel theaterListPanel;
        javax.swing.JPanel theater_lineleft;
        javax.swing.JPanel theater_lineright;
        javax.swing.JLabel theatertext;
        javax.swing.JPanel MovieLab;
        javax.swing.JLabel movieSelectionLabel;
        javax.swing.JPanel rightSepMoviePanel;
        javax.swing.JPanel leftSepMoviePanel;
        mainpanel = new javax.swing.JPanel();
        poster = new javax.swing.JLabel();
        MovieLab = new javax.swing.JPanel();
        movieSelectionLabel = new javax.swing.JLabel();
        rightSepMoviePanel = new javax.swing.JPanel();
        leftSepMoviePanel = new javax.swing.JPanel();
        movieListPanel = new javax.swing.JPanel();
        theaterLab = new javax.swing.JPanel();
        theatertext = new javax.swing.JLabel();
        theater_lineright = new javax.swing.JPanel();
        theater_lineleft = new javax.swing.JPanel();
        theaterListPanel = new javax.swing.JPanel();
        mainpanel.setBackground(new java.awt.Color(38, 19, 66));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MovieLab.setBackground(new java.awt.Color(38, 19, 66));
        MovieLab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        poster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/poster.jpg"))); // NOI18N
        mainpanel.add(poster, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 890, -1));

        movieSelectionLabel.setBackground(new java.awt.Color(0, 0, 51));
        movieSelectionLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        movieSelectionLabel.setForeground(new java.awt.Color(255, 255, 255));
        movieSelectionLabel.setText("MOVIE SELECTIONS");
        MovieLab.add(movieSelectionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 309, -1));

        javax.swing.GroupLayout rightSepMoviePanelLayout = new javax.swing.GroupLayout(rightSepMoviePanel);
        rightSepMoviePanel.setLayout(rightSepMoviePanelLayout);
        rightSepMoviePanelLayout.setHorizontalGroup(
                rightSepMoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
        rightSepMoviePanelLayout.setVerticalGroup(
                rightSepMoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 5, Short.MAX_VALUE)
        );

        MovieLab.add(rightSepMoviePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 300, 5));

        javax.swing.GroupLayout leftSepMoviePanelLayout = new javax.swing.GroupLayout(leftSepMoviePanel);
        leftSepMoviePanel.setLayout(leftSepMoviePanelLayout);
        leftSepMoviePanelLayout.setHorizontalGroup(
                leftSepMoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
        leftSepMoviePanelLayout.setVerticalGroup(
                leftSepMoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 5, Short.MAX_VALUE)
        );

        MovieLab.add(leftSepMoviePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, 5));

        mainpanel.add(MovieLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 960, 40));

        movieListPanel.setBackground(new java.awt.Color(38, 19, 66));
        movieListPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ArrayList<Film> fi = CustomerController.getAllFilms();
        createListMoviePanel(movieListPanel,fi);
        mainpanel.add(movieListPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 285, 960, 840));
        theaterLab.setBackground(new java.awt.Color(38, 19, 66));
        theaterLab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        theatertext.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        theatertext.setForeground(new java.awt.Color(255, 255, 255));
        theatertext.setText("THEATERS");
        theaterLab.add(theatertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 309, 40));

        javax.swing.GroupLayout theater_linerightLayout = new javax.swing.GroupLayout(theater_lineright);
        theater_lineright.setLayout(theater_linerightLayout);
        theater_linerightLayout.setHorizontalGroup(
                theater_linerightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
        theater_linerightLayout.setVerticalGroup(
                theater_linerightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 5, Short.MAX_VALUE)
        );

        theaterLab.add(theater_lineright, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 300, 5));

        javax.swing.GroupLayout theater_lineleftLayout = new javax.swing.GroupLayout(theater_lineleft);
        theater_lineleft.setLayout(theater_lineleftLayout);
        theater_lineleftLayout.setHorizontalGroup(
                theater_lineleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
        theater_lineleftLayout.setVerticalGroup(
                theater_lineleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 5, Short.MAX_VALUE)
        );

        theaterLab.add(theater_lineleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, 5));

        mainpanel.add(theaterLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1135, 960, 40));

        theaterListPanel.setBackground(new java.awt.Color(38, 19, 66));
        theaterListPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ArrayList<Theater> theaters = CustomerController.getAllTheaters();
        createListTheaterPanel(theaterListPanel,theaters);

        mainpanel.add(theaterListPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1175, 960, 320));
        mainscrollpane.setViewportView(mainpanel);
        return mainpanel;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView(new Customer(1,"Nguyễn Phạm Thanh Vy","","","","",0,"")).setVisible(true);
            }
        });
    }
    private Customer customer;
    public javax.swing.JPanel bg;
    public javax.swing.JPanel mainpanel;
    public javax.swing.JScrollPane mainscrollpane;
    private javax.swing.JPanel sidepane;
    public javax.swing.JPanel bookingpanel;
    public javax.swing.JPanel personalpanel;
    private Boolean home_onclick = true;
    private Boolean bookticket_onclick = false;
    private Boolean personal_onclick = false;
    // End of variables declaration                   
}
