/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AdminController;
import Model.Admin;
import Model.Customer;
import Model.User;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class EditAnUser extends javax.swing.JFrame {
    int mpX, mpY;
    /**
     * Creates new form AddAnUser
     */
    User user = null;
    Customer cus = null;
    MannageUsers parent =null;
    int ID =0;
    public EditAnUser(MannageUsers parent, int ID) {
        this.ID = ID;
        this.parent = parent;
        user = AdminController.searchAnUser(ID, 0);
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(radio_admin);
        group.add(radio_cus);
        if(user.IsAdmin())
            radio_admin.setSelected(true);
        fullname.setText(user.getFullname());
        String[] dateofbirth = user.getDoB().split(" ")[0].split("-");
        //System.out.println(dateofbirth[1]);
        int y = Integer.parseInt(dateofbirth[0]);
        int m = Integer.parseInt(dateofbirth[1]);
        int d = Integer.parseInt(dateofbirth[2]);
        year.setSelectedItem(Integer.toString(y));
        month.setSelectedItem(Integer.toString(m));
        date.setSelectedItem(Integer.toString(d));
        //(String)year.getSelectedItem() + "/" + (String)month.getSelectedItem() + "/" + (String)date.getSelectedItem();
        //System.out.println(dateofbirth);
        username.setText(user.getUsername());
        phone.setText(user.getPhone());
        if(radio_cus.isSelected()){
            String[] favgenre = user.getGenre().split(", ");
            for(String genre:favgenre){
                if(genre.equals("Drama"))
                    genre_drama.setSelected(true);
                if(genre.equals("Comedy"))
                    genre_comedy.setSelected(true);
                if(genre.equals("Action"))
                    genre_action.setSelected(true);
            }
            
        }
         
            

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_type = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jBut_SignUp = new javax.swing.JButton();
        detail = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        lab_type6 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        radio_admin = new javax.swing.JRadioButton();
        radio_cus = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lab_type1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        fullname = new javax.swing.JTextField();
        lab_cfname = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lab_type2 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lab_cfname1 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        date = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        lab_type3 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        lab_cusername = new javax.swing.JLabel();
        lab_cusername1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        lab_type4 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        phone = new javax.swing.JTextField();
        lab_cphone = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        bg_genre = new javax.swing.JPanel();
        lab_genre = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        genre_drama = new javax.swing.JCheckBox();
        genre_comedy = new javax.swing.JCheckBox();
        genre_action = new javax.swing.JCheckBox();

        lab_type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type.setForeground(new java.awt.Color(255, 255, 255));
        lab_type.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_type.setText("Type of Account");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(64, 33, 100));
        setMinimumSize(new java.awt.Dimension(575, 402));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(64, 33, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(64, 33, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btn_exit.setBackground(new java.awt.Color(64, 33, 100));
        btn_exit.setPreferredSize(new java.awt.Dimension(40, 30));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        btn_exit.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 30));
        btn_exit.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(btn_exit, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        main.setBackground(new java.awt.Color(64, 33, 100));
        main.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(64, 33, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(640, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FORM EDIT AN USER");
        jPanel3.add(jLabel2, java.awt.BorderLayout.CENTER);

        main.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        footer.setBackground(new java.awt.Color(64, 33, 100));
        footer.setPreferredSize(new java.awt.Dimension(640, 50));

        jBut_SignUp.setBackground(new java.awt.Color(255, 255, 255));
        jBut_SignUp.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jBut_SignUp.setForeground(new java.awt.Color(64, 33, 100));
        jBut_SignUp.setText("Save");
        jBut_SignUp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut_SignUp.setBorderPainted(false);
        jBut_SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBut_SignUp.setPreferredSize(new java.awt.Dimension(100, 29));
        jBut_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_SignUpActionPerformed(evt);
            }
        });
        footer.add(jBut_SignUp);

        main.add(footer, java.awt.BorderLayout.PAGE_END);

        detail.setBackground(new java.awt.Color(64, 33, 100));
        detail.setLayout(new java.awt.GridLayout(6, 1, 10, 10));

        jPanel4.setBackground(new java.awt.Color(64, 33, 100));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(64, 33, 100));
        jPanel11.setMinimumSize(new java.awt.Dimension(150, 100));
        jPanel11.setPreferredSize(new java.awt.Dimension(175, 100));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11, java.awt.BorderLayout.WEST);

        jPanel12.setBackground(new java.awt.Color(64, 33, 100));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel23.setBackground(new java.awt.Color(64, 33, 100));
        jPanel23.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel24.setBackground(new java.awt.Color(64, 33, 100));
        jPanel24.setPreferredSize(new java.awt.Dimension(165, 37));
        jPanel24.setLayout(new java.awt.BorderLayout(10, 10));

        lab_type6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type6.setForeground(new java.awt.Color(255, 255, 255));
        lab_type6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_type6.setText("Type of Account");
        jPanel24.add(lab_type6, java.awt.BorderLayout.CENTER);

        jPanel23.add(jPanel24, java.awt.BorderLayout.WEST);

        jPanel25.setBackground(new java.awt.Color(64, 33, 100));
        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        radio_admin.setBackground(new java.awt.Color(64, 33, 100));
        radio_admin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_admin.setForeground(new java.awt.Color(255, 255, 255));
        radio_admin.setText("Admin");
        radio_admin.setEnabled(false);
        radio_admin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radio_adminStateChanged(evt);
            }
        });
        jPanel25.add(radio_admin);

        radio_cus.setBackground(new java.awt.Color(64, 33, 100));
        radio_cus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_cus.setForeground(new java.awt.Color(255, 255, 255));
        radio_cus.setSelected(true);
        radio_cus.setText("Customer");
        radio_cus.setEnabled(false);
        radio_cus.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radio_cusStateChanged(evt);
            }
        });
        jPanel25.add(radio_cus);

        jPanel23.add(jPanel25, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel23, java.awt.BorderLayout.PAGE_START);

        detail.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(64, 33, 100));
        jPanel5.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel13.setBackground(new java.awt.Color(64, 33, 100));
        jPanel13.setPreferredSize(new java.awt.Dimension(165, 37));
        jPanel13.setLayout(new java.awt.BorderLayout(10, 10));

        lab_type1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type1.setForeground(new java.awt.Color(255, 255, 255));
        lab_type1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_type1.setText("Full Name");
        jPanel13.add(lab_type1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel13, java.awt.BorderLayout.WEST);

        jPanel14.setBackground(new java.awt.Color(64, 33, 100));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        fullname.setPreferredSize(new java.awt.Dimension(300, 30));
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel14.add(fullname);

        lab_cfname.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel14.add(lab_cfname);

        jPanel5.add(jPanel14, java.awt.BorderLayout.CENTER);

        detail.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(64, 33, 100));
        jPanel6.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel15.setBackground(new java.awt.Color(64, 33, 100));
        jPanel15.setPreferredSize(new java.awt.Dimension(165, 37));
        jPanel15.setLayout(new java.awt.BorderLayout(10, 10));

        lab_type2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type2.setForeground(new java.awt.Color(255, 255, 255));
        lab_type2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_type2.setText("DOB");
        jPanel15.add(lab_type2, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel15, java.awt.BorderLayout.WEST);

        jPanel16.setBackground(new java.awt.Color(64, 33, 100));
        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lab_cfname1.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel16.add(lab_cfname1);

        year.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jPanel16.add(year);

        month.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel16.add(month);

        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jPanel16.add(date);

        jPanel6.add(jPanel16, java.awt.BorderLayout.CENTER);

        detail.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(64, 33, 100));
        jPanel7.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel17.setBackground(new java.awt.Color(64, 33, 100));
        jPanel17.setPreferredSize(new java.awt.Dimension(165, 37));
        jPanel17.setLayout(new java.awt.BorderLayout(10, 10));

        lab_type3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type3.setForeground(new java.awt.Color(255, 255, 255));
        lab_type3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_type3.setText("Username");
        jPanel17.add(lab_type3, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel17, java.awt.BorderLayout.WEST);

        jPanel18.setBackground(new java.awt.Color(64, 33, 100));
        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        username.setEnabled(false);
        username.setPreferredSize(new java.awt.Dimension(300, 30));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel18.add(username);

        lab_cusername.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel18.add(lab_cusername);

        lab_cusername1.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel18.add(lab_cusername1);

        jPanel7.add(jPanel18, java.awt.BorderLayout.CENTER);

        detail.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(64, 33, 100));
        jPanel8.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel19.setBackground(new java.awt.Color(64, 33, 100));
        jPanel19.setPreferredSize(new java.awt.Dimension(165, 37));
        jPanel19.setLayout(new java.awt.BorderLayout(10, 10));

        lab_type4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_type4.setForeground(new java.awt.Color(255, 255, 255));
        lab_type4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_type4.setText("Phone");
        jPanel19.add(lab_type4, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel19, java.awt.BorderLayout.WEST);

        jPanel20.setBackground(new java.awt.Color(64, 33, 100));
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        phone.setPreferredSize(new java.awt.Dimension(300, 30));
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel20.add(phone);

        lab_cphone.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel20.add(lab_cphone);

        jPanel8.add(jPanel20, java.awt.BorderLayout.CENTER);

        detail.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(64, 33, 100));
        jPanel9.setLayout(new java.awt.BorderLayout(20, 20));

        bg_genre.setBackground(new java.awt.Color(64, 33, 100));
        bg_genre.setPreferredSize(new java.awt.Dimension(165, 37));
        bg_genre.setLayout(new java.awt.BorderLayout(10, 10));

        lab_genre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_genre.setForeground(new java.awt.Color(255, 255, 255));
        lab_genre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_genre.setText("Favourite Genre");
        bg_genre.add(lab_genre, java.awt.BorderLayout.CENTER);

        jPanel9.add(bg_genre, java.awt.BorderLayout.WEST);

        jPanel22.setBackground(new java.awt.Color(64, 33, 100));
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        genre_drama.setBackground(new java.awt.Color(64, 33, 100));
        genre_drama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_drama.setForeground(new java.awt.Color(255, 255, 255));
        genre_drama.setSelected(true);
        genre_drama.setText("Drama");
        jPanel22.add(genre_drama);

        genre_comedy.setBackground(new java.awt.Color(64, 33, 100));
        genre_comedy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_comedy.setForeground(new java.awt.Color(255, 255, 255));
        genre_comedy.setSelected(true);
        genre_comedy.setText("Comedy");
        jPanel22.add(genre_comedy);

        genre_action.setBackground(new java.awt.Color(64, 33, 100));
        genre_action.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre_action.setForeground(new java.awt.Color(255, 255, 255));
        genre_action.setSelected(true);
        genre_action.setText("Action");
        jPanel22.add(genre_action);

        jPanel9.add(jPanel22, java.awt.BorderLayout.CENTER);

        detail.add(jPanel9);

        main.add(detail, java.awt.BorderLayout.CENTER);

        jPanel1.add(main, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(640, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        this.dispose();
        parent.showTable();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        // TODO add your handling code here:
        btn_exit.setBackground(Color.red);
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        // TODO add your handling code here:
        btn_exit.setBackground(new Color(64,33,100));

    }//GEN-LAST:event_btn_exitMouseExited

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void jBut_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_SignUpActionPerformed
        // TODO add your handling code here:
        String full_name = fullname.getText();
        String user_name = username.getText();
        //String pass = String.valueOf(password.getPassword());
        String dateofbirth = (String)year.getSelectedItem() + "/" + (String)month.getSelectedItem() + "/" + (String)date.getSelectedItem();
        System.out.println(dateofbirth);
        String phonenum = phone.getText();
        
        if(radio_admin.isSelected()){
            boolean check = AdminController.updateAnUser(new Admin(ID, full_name, dateofbirth, phonenum, user_name,user.getPassword() ));
            if(!check){
                JOptionPane.showMessageDialog(this, "Something went wrong", "Information", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Update succesfully", "Information", JOptionPane.INFORMATION_MESSAGE);
            
            }
        }
        else{
            String favgenre = "";
            if (genre_drama.isSelected())
            favgenre += genre_drama.getText() + ", ";
            if (genre_action.isSelected())
            favgenre += genre_action.getText() + ", ";
            if (genre_comedy.isSelected())
            favgenre += genre_comedy.getText() + ", ";
            if (favgenre.length() != 0){
                favgenre = favgenre.substring(0, favgenre.length() - 2);
            boolean check = AdminController.updateACustomer(new Customer(ID, full_name, dateofbirth, user_name, user.getPassword(), phonenum, 0, favgenre));
            if(!check){
                JOptionPane.showMessageDialog(this, "Something went wrong", "Information", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Sign up succesfully", "Information", JOptionPane.INFORMATION_MESSAGE);
            
            }   
        }
    }
        
    }//GEN-LAST:event_jBut_SignUpActionPerformed

    private void radio_adminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radio_adminStateChanged
        // TODO add your handling code here:[32,33,35]
        if(radio_admin.isSelected()){
//            lab_genre.setForeground(new Color(64,33,100));
//            genre_action.setForeground(new Color(64,33,100));
//            genre_comedy.setForeground(new Color(64,33,100));
//            genre_drama.setForeground(new Color(64,33,100));
            genre_action.setVisible(false);
            genre_drama.setVisible(false);
            genre_comedy.setVisible(false);
            lab_genre.setVisible(false);
        }
        else{
//            lab_genre.setForeground(new Color(255,255,255));
//            genre_action.setForeground(new Color(255,255,255));
//            genre_comedy.setForeground(new Color(255,255,255));
//            genre_drama.setForeground(new Color(255,255,255));
            genre_action.setVisible(true);
            genre_drama.setVisible(true);
            genre_comedy.setVisible(true);
            lab_genre.setVisible(true);
        }
    }//GEN-LAST:event_radio_adminStateChanged

    private void radio_cusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radio_cusStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_cusStateChanged

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        ArrayList<User> lstUser = null;
        System.out.println(username.getText()+"11"+fullname.getText());
        if(username.getText().equals(""))
            return;
        
        lstUser = AdminController.searchUsers(username.getText(),0);
        
        System.out.println(lstUser+"  list");
        if(lstUser.size()==0){
            lab_cusername1.setVisible(false); 
            lab_cusername.setVisible(true);
            lab_cusername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok.png")));
        }
        else{
            lab_cusername.setVisible(false);
            lab_cusername1.setVisible(true);
            lab_cusername1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png")));
        }
    }//GEN-LAST:event_usernameFocusLost

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        // TODO add your handling code here:
        String key = phone.getText();
        if(key.length()>10){
            lab_cphone.setVisible(true);
            lab_cphone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png")));
            return;
        }
       
        for(int i = 0;i<key.length();i++){
            if(!(key.charAt(i)<='9' &&key.charAt(i)>='0')){
                lab_cphone.setVisible(true);
                lab_cphone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png")));
                return;
            }
        }
        lab_cphone.setVisible(false);
    }//GEN-LAST:event_phoneFocusLost

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        mpX = evt.getX();
        mpY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        setLocation(getLocation().x + evt.getX() - mpX,getLocation().y + evt.getY() - mpY );
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_genre;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JPanel detail;
    private javax.swing.JPanel footer;
    private javax.swing.JTextField fullname;
    private javax.swing.JCheckBox genre_action;
    private javax.swing.JCheckBox genre_comedy;
    private javax.swing.JCheckBox genre_drama;
    private javax.swing.JButton jBut_SignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lab_cfname;
    private javax.swing.JLabel lab_cfname1;
    private javax.swing.JLabel lab_cphone;
    private javax.swing.JLabel lab_cusername;
    private javax.swing.JLabel lab_cusername1;
    private javax.swing.JLabel lab_genre;
    private javax.swing.JLabel lab_type;
    private javax.swing.JLabel lab_type1;
    private javax.swing.JLabel lab_type2;
    private javax.swing.JLabel lab_type3;
    private javax.swing.JLabel lab_type4;
    private javax.swing.JLabel lab_type6;
    private javax.swing.JPanel main;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField phone;
    private javax.swing.JRadioButton radio_admin;
    private javax.swing.JRadioButton radio_cus;
    private javax.swing.JTextField username;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
