/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Controller.AdminController;
import Model.*;
import javax.swing.JOptionPane;
/**
 *
 * @author nguye
 */
public class MannageUsers extends javax.swing.JFrame {

    /**
     * Creates new form MannageUsers
     */
    DefaultTableModel deftab;
    int mpX, mpY;
    Admin admin = null;
    public MannageUsers(Admin admin) {
        this.admin = admin;
        initComponents();
        
        deftab = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }
        };
        ArrayList<User> lstUsers = AdminController.getAllUsers();
        tab.setModel(deftab);
        deftab.addColumn("ID");
        deftab.addColumn("Full Name");
        
        deftab.addColumn("DOB");
        deftab.addColumn("Username");
        deftab.addColumn("Phone");
        deftab.addColumn("Point");
        deftab.addColumn("Favourite Genre");
        deftab.addColumn("Is Admin");
        deftab.setRowCount(0);
        for(User s:lstUsers){
            System.out.println(s.getObject());
            deftab.addRow(s.getObject());
            
        }
        
              
        
        //System.out.println(getClass().getResource("/images/exit.png"));
        //System.out.println(getClass().getResource("/images/logo.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        header_top = new javax.swing.JPanel();
        menu_top = new javax.swing.JPanel();
        btn_exit = new javax.swing.JPanel();
        lab_exit = new javax.swing.JLabel();
        btn_min = new javax.swing.JPanel();
        lab_min = new javax.swing.JLabel();
        btn_max = new javax.swing.JPanel();
        lab_max = new javax.swing.JLabel();
        header_bottom = new javax.swing.JPanel();
        main_menu = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        lab_home = new javax.swing.JLabel();
        btn_accounts = new javax.swing.JPanel();
        lab_accounts = new javax.swing.JLabel();
        btn_films = new javax.swing.JPanel();
        lab_films = new javax.swing.JLabel();
        btn_showtimes = new javax.swing.JPanel();
        lab_showtimes = new javax.swing.JLabel();
        btn_revenue = new javax.swing.JPanel();
        lab_revenue = new javax.swing.JLabel();
        logout_pannel = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        menu_search = new javax.swing.JPanel();
        menu_btns = new javax.swing.JPanel();
        search = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        type = new javax.swing.JPanel();
        checkboxAdmin = new javax.swing.JPanel();
        cboxAdmin = new javax.swing.JCheckBox();
        checkboxCus = new javax.swing.JPanel();
        cboxCus = new javax.swing.JCheckBox();
        menu_crud = new javax.swing.JPanel();
        crud = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JLabel();
        btnAdd = new javax.swing.JLabel();
        btnDel = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        menu_main = new javax.swing.JPanel();
        blank = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        header.setBackground(new java.awt.Color(64, 33, 100));
        header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        header.setPreferredSize(new java.awt.Dimension(800, 80));
        header.setLayout(new java.awt.BorderLayout());

        header_top.setBackground(new java.awt.Color(64, 33, 100));
        header_top.setPreferredSize(new java.awt.Dimension(400, 30));
        header_top.setLayout(new java.awt.BorderLayout());

        menu_top.setBackground(new java.awt.Color(64, 33, 100));
        menu_top.setPreferredSize(new java.awt.Dimension(150, 30));
        menu_top.setLayout(new java.awt.BorderLayout());

        btn_exit.setBackground(new java.awt.Color(64, 33, 100));
        btn_exit.setMinimumSize(new java.awt.Dimension(25, 25));
        btn_exit.setPreferredSize(new java.awt.Dimension(50, 30));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        btn_exit.setLayout(new java.awt.BorderLayout());

        lab_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        lab_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_exit.add(lab_exit, java.awt.BorderLayout.CENTER);

        menu_top.add(btn_exit, java.awt.BorderLayout.EAST);

        btn_min.setBackground(new java.awt.Color(64, 33, 100));
        btn_min.setPreferredSize(new java.awt.Dimension(50, 30));
        btn_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minMouseExited(evt);
            }
        });
        btn_min.setLayout(new java.awt.BorderLayout());

        lab_min.setBackground(new java.awt.Color(24, 24, 24));
        lab_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/min.png"))); // NOI18N
        lab_min.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lab_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab_minMouseExited(evt);
            }
        });
        btn_min.add(lab_min, java.awt.BorderLayout.CENTER);

        menu_top.add(btn_min, java.awt.BorderLayout.WEST);

        btn_max.setBackground(new java.awt.Color(64, 33, 100));
        btn_max.setPreferredSize(new java.awt.Dimension(50, 30));
        btn_max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_maxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_maxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_maxMouseExited(evt);
            }
        });
        btn_max.setLayout(new java.awt.BorderLayout());

        lab_max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/max.png"))); // NOI18N
        btn_max.add(lab_max, java.awt.BorderLayout.CENTER);

        menu_top.add(btn_max, java.awt.BorderLayout.CENTER);

        header_top.add(menu_top, java.awt.BorderLayout.LINE_END);

        header.add(header_top, java.awt.BorderLayout.PAGE_START);

        header_bottom.setBackground(new java.awt.Color(64, 33, 100));
        header_bottom.setAlignmentX(Component.CENTER_ALIGNMENT);
        header_bottom.setMinimumSize(new java.awt.Dimension(800, 30));
        header_bottom.setPreferredSize(new java.awt.Dimension(800, 50));

        main_menu.setBackground(new java.awt.Color(64, 33, 100));
        main_menu.setPreferredSize(new java.awt.Dimension(700, 30));
        main_menu.setLayout(new java.awt.GridLayout(1, 6));

        btn_home.setBackground(new java.awt.Color(64, 33, 100));
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.setLayout(new java.awt.BorderLayout());

        lab_home.setBackground(new java.awt.Color(64, 33, 100));
        lab_home.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_home.setForeground(new java.awt.Color(255, 255, 255));
        lab_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        lab_home.setText("Home");
        lab_home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_home.add(lab_home, java.awt.BorderLayout.CENTER);

        main_menu.add(btn_home);

        btn_accounts.setBackground(new java.awt.Color(64, 33, 100));
        btn_accounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_accountsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_accountsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_accountsMouseExited(evt);
            }
        });
        btn_accounts.setLayout(new java.awt.BorderLayout());

        lab_accounts.setBackground(new java.awt.Color(64, 33, 100));
        lab_accounts.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lab_accounts.setForeground(new java.awt.Color(255, 255, 255));
        lab_accounts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_accounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account1.png"))); // NOI18N
        lab_accounts.setText("Accounts");
        lab_accounts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_accounts.add(lab_accounts, java.awt.BorderLayout.CENTER);

        main_menu.add(btn_accounts);

        btn_films.setBackground(new java.awt.Color(64, 33, 100));
        btn_films.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_filmsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_filmsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_filmsMouseExited(evt);
            }
        });
        btn_films.setLayout(new java.awt.BorderLayout());

        lab_films.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_films.setForeground(new java.awt.Color(255, 255, 255));
        lab_films.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_films.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/film.png"))); // NOI18N
        lab_films.setText("Films");
        lab_films.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_films.add(lab_films, java.awt.BorderLayout.CENTER);

        main_menu.add(btn_films);

        btn_showtimes.setBackground(new java.awt.Color(64, 33, 100));
        btn_showtimes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showtimesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_showtimesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_showtimesMouseExited(evt);
            }
        });
        btn_showtimes.setLayout(new java.awt.BorderLayout());

        lab_showtimes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_showtimes.setForeground(new java.awt.Color(255, 255, 255));
        lab_showtimes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_showtimes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/showtimes.png"))); // NOI18N
        lab_showtimes.setText("Showtimes");
        lab_showtimes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_showtimes.add(lab_showtimes, java.awt.BorderLayout.CENTER);

        main_menu.add(btn_showtimes);

        btn_revenue.setBackground(new java.awt.Color(64, 33, 100));
        btn_revenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_revenueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_revenueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_revenueMouseExited(evt);
            }
        });
        btn_revenue.setLayout(new java.awt.BorderLayout());

        lab_revenue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_revenue.setForeground(new java.awt.Color(255, 255, 255));
        lab_revenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_revenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/revenue.png"))); // NOI18N
        lab_revenue.setText(" Revenue");
        lab_revenue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_revenue.add(lab_revenue, java.awt.BorderLayout.CENTER);

        main_menu.add(btn_revenue);

        logout_pannel.setBackground(new java.awt.Color(64, 33, 100));
        logout_pannel.setLayout(new java.awt.BorderLayout());

        logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.setText("Log out");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout_pannel.add(logout, java.awt.BorderLayout.CENTER);

        main_menu.add(logout_pannel);

        header_bottom.add(main_menu);

        header.add(header_bottom, java.awt.BorderLayout.CENTER);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.BorderLayout());

        menu_search.setBackground(new java.awt.Color(255, 255, 255));
        menu_search.setPreferredSize(new java.awt.Dimension(800, 50));
        menu_search.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        menu_btns.setBackground(new java.awt.Color(255, 255, 255));
        menu_btns.setPreferredSize(new java.awt.Dimension(500, 30));
        menu_btns.setLayout(new java.awt.BorderLayout(5, 0));

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setPreferredSize(new java.awt.Dimension(300, 50));
        search.setLayout(new java.awt.BorderLayout());

        txtSearch.setPreferredSize(new java.awt.Dimension(190, 20));
        search.add(txtSearch, java.awt.BorderLayout.WEST);

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setForeground(new java.awt.Color(122, 72, 221));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSearch.setPreferredSize(new java.awt.Dimension(50, 30));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        search.add(btnSearch, java.awt.BorderLayout.CENTER);

        menu_btns.add(search, java.awt.BorderLayout.WEST);

        type.setLayout(new java.awt.BorderLayout());

        checkboxAdmin.setBackground(new java.awt.Color(255, 255, 255));
        checkboxAdmin.setPreferredSize(new java.awt.Dimension(90, 30));

        cboxAdmin.setBackground(new java.awt.Color(255, 255, 255));
        cboxAdmin.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cboxAdmin.setSelected(true);
        cboxAdmin.setText("Admin");
        cboxAdmin.setRolloverEnabled(false);
        cboxAdmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cboxAdminStateChanged(evt);
            }
        });
        checkboxAdmin.add(cboxAdmin);

        type.add(checkboxAdmin, java.awt.BorderLayout.WEST);

        checkboxCus.setBackground(new java.awt.Color(255, 255, 255));

        cboxCus.setBackground(new java.awt.Color(255, 255, 255));
        cboxCus.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cboxCus.setSelected(true);
        cboxCus.setText("Customer");
        cboxCus.setRolloverEnabled(false);
        cboxCus.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cboxCusStateChanged(evt);
            }
        });
        checkboxCus.add(cboxCus);

        type.add(checkboxCus, java.awt.BorderLayout.CENTER);

        menu_btns.add(type, java.awt.BorderLayout.CENTER);

        menu_search.add(menu_btns);

        body.add(menu_search, java.awt.BorderLayout.PAGE_START);

        menu_crud.setBackground(new java.awt.Color(255, 255, 255));
        menu_crud.setPreferredSize(new java.awt.Dimension(150, 100));

        crud.setBackground(new java.awt.Color(255, 255, 255));
        crud.setPreferredSize(new java.awt.Dimension(100, 200));
        crud.setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(122, 72, 221));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefreshMouseExited(evt);
            }
        });
        crud.add(btnRefresh);

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(122, 72, 221));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        crud.add(btnAdd);

        btnDel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDel.setForeground(new java.awt.Color(122, 72, 221));
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete1.png"))); // NOI18N
        btnDel.setText("Delete");
        btnDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelMouseExited(evt);
            }
        });
        crud.add(btnDel);

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(122, 72, 221));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        crud.add(btnUpdate);

        menu_crud.add(crud);

        body.add(menu_crud, java.awt.BorderLayout.LINE_END);

        menu_main.setBackground(new java.awt.Color(255, 255, 255));
        menu_main.setLayout(new java.awt.BorderLayout(10, 10));

        blank.setBackground(new java.awt.Color(255, 255, 255));
        menu_main.add(blank, java.awt.BorderLayout.WEST);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tab.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        tab.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tab.setAutoscrolls(false);
        tab.setMinimumSize(new java.awt.Dimension(15, 64));
        tab.setPreferredSize(new java.awt.Dimension(350, 350));
        tab.setRowHeight(25);
        tab.setSelectionBackground(new Color(122,72,221)
        );
        tab.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tab.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tab.setShowGrid(false);
        jScrollPane1.setViewportView(tab);

        menu_main.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        body.add(menu_main, java.awt.BorderLayout.CENTER);

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        // TODO add your handling code here:
        btn_exit.setBackground(Color.red);
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        // TODO add your handling code here:
        btn_exit.setBackground(new Color(64,33,100));
    }//GEN-LAST:event_btn_exitMouseExited

    private void btn_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_minMouseClicked

    private void btn_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseEntered
        // TODO add your handling code here:
        btn_min.setBackground(Color.red);
    }//GEN-LAST:event_btn_minMouseEntered

    private void btn_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseExited
        // TODO add your handling code here:
        btn_min.setBackground(new Color(64,33,100));
    }//GEN-LAST:event_btn_minMouseExited

    private void btn_maxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maxMouseClicked
        // TODO add your handling code here:
        if(this.getExtendedState()!=MAXIMIZED_BOTH){
            this.setExtendedState(MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(NORMAL);
        }
    }//GEN-LAST:event_btn_maxMouseClicked

    private void btn_maxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maxMouseEntered
        // TODO add your handling code here:
        btn_max.setBackground(new Color(37,12,65));
    }//GEN-LAST:event_btn_maxMouseEntered

    private void btn_maxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maxMouseExited
        // TODO add your handling code here:
        btn_max.setBackground(new Color(64,33,100));
    }//GEN-LAST:event_btn_maxMouseExited

    private void cboxAdminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cboxAdminStateChanged
        // TODO add your handling code here:
        showTable();
    }//GEN-LAST:event_cboxAdminStateChanged

    private void cboxCusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cboxCusStateChanged
        // TODO add your handling code here:
        showTable();
    }//GEN-LAST:event_cboxCusStateChanged

    private void btnRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseEntered
        // TODO add your handling code here:
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14));
    }//GEN-LAST:event_btnRefreshMouseEntered

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        // TODO add your handling code here:
        cboxAdmin.setSelected(true);
        cboxCus.setSelected(true);
        txtSearch.setText("");
        ArrayList<User> lstUsers = AdminController.getAllUsers();
        deftab.setRowCount(0);
        for(User s:lstUsers){
            System.out.println(s.getObject());
            deftab.addRow(s.getObject());
        }
            
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnRefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseExited
        // TODO add your handling code here:
        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 14));
    }//GEN-LAST:event_btnRefreshMouseExited

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        new AddAnUser(this).setVisible(true);
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        // TODO add your handling code here:
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14));
        
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        // TODO add your handling code here:
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14));
    }//GEN-LAST:event_btnAddMouseExited

    private void btnDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseClicked
        // TODO add your handling code here:
        int row = tab.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Please choose one row to delete","Remind",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int confirm= JOptionPane.showConfirmDialog(this, "Do you really want to delete this row");
            if (confirm == JOptionPane.YES_OPTION){
                int idDel = Integer.valueOf(String.valueOf(tab.getValueAt(row, 0)));
                AdminController.deleteAnUser(idDel);
            }
        }
        
        showTable();
    }//GEN-LAST:event_btnDelMouseClicked

    private void btnDelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseEntered
        // TODO add your handling code here:
        btnDel.setFont(new java.awt.Font("Tahoma", 1, 14));
    }//GEN-LAST:event_btnDelMouseEntered

    private void btnDelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseExited
        // TODO add your handling code here:
        btnDel.setFont(new java.awt.Font("Tahoma", 0, 14));
    }//GEN-LAST:event_btnDelMouseExited

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        int row = tab.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Please choose one row to edit","Remind",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int id = Integer.valueOf(String.valueOf(tab.getValueAt(row, 0)));
            new EditAnUser(this,id).setVisible(true);
            //this.dispose();
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        // TODO add your handling code here:
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14));
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        // TODO add your handling code here:
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14));
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // TODO add your handling code here:
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12));
        
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        // TODO add your handling code here:
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 12));
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String key = txtSearch.getText();
        System.out.println(key);
        if(key.equals("")){
            
            JOptionPane.showMessageDialog(this, "Please enter ID or Username of accounts you need to find","Remind",JOptionPane.INFORMATION_MESSAGE);
        
        }
        else{
            int type = 0 ;
            if(cboxAdmin.isSelected()&&cboxCus.isSelected())
                type=0;
            if(!cboxAdmin.isSelected()&&cboxCus.isSelected())
                type=1;
            if(cboxAdmin.isSelected()&&!cboxCus.isSelected())
                type=2;
            try{
                int id = Integer.parseInt(key);
                User s = AdminController.searchAnUser(id,type);
                deftab.setRowCount(0);
                if(s!=null)
                    deftab.addRow(s.getObject());
            }catch(NumberFormatException nfe){
                System.out.println(nfe);
                ArrayList<User> lstUsers = AdminController.searchUsers(key,type);
                deftab.setRowCount(0);
                System.out.println(lstUsers);
                for(User s:lstUsers){
                    System.out.println(s.getObject());
                    deftab.addRow(s.getObject());
            
        }
            }
            
            
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void lab_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_minMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
        
    }//GEN-LAST:event_lab_minMouseClicked

    private void lab_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_minMouseEntered
        // TODO add your handling code here:
        btn_min.setBackground(new Color(37,12,65));
    }//GEN-LAST:event_lab_minMouseEntered

    private void lab_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_minMouseExited
        // TODO add your handling code here:
        btn_min.setBackground(new Color(64,33,100));
    }//GEN-LAST:event_lab_minMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        mpX = evt.getX();
        mpY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        setLocation(getLocation().x + evt.getX() - mpX,getLocation().y + evt.getY() - mpY );
    }//GEN-LAST:event_formMouseDragged

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        // TODO add your handling code here:
        new AdminView(admin).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setBackground(new Color(37,12,65));
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setBackground(new Color(64,33,100));
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_accountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accountsMouseClicked
        // TODO add your handling code here:
        new MannageUsers(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_accountsMouseClicked

    private void btn_accountsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accountsMouseEntered
        // TODO add your handling code here:
        btn_accounts.setBackground(new Color(37,12,65));
    }//GEN-LAST:event_btn_accountsMouseEntered

    private void btn_accountsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accountsMouseExited
        // TODO add your handling code here:
        btn_accounts.setBackground(new Color(64,33,100));
    }//GEN-LAST:event_btn_accountsMouseExited

    private void btn_filmsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_filmsMouseClicked
        // TODO add your handling code here:
        new ManageFilms(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_filmsMouseClicked

    private void btn_filmsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_filmsMouseEntered
        // TODO add your handling code here:
        btn_films.setBackground(new Color(37,12,65));
    }//GEN-LAST:event_btn_filmsMouseEntered

    private void btn_filmsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_filmsMouseExited
        // TODO add your handling code here:
        btn_films.setBackground(new Color(64,33,100));
    }//GEN-LAST:event_btn_filmsMouseExited

    private void btn_showtimesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showtimesMouseClicked
        // TODO add your handling code here:
        new ManageShowtimes(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_showtimesMouseClicked

    private void btn_showtimesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showtimesMouseEntered
        // TODO add your handling code here:
        btn_showtimes.setBackground(new Color(37,12,65));
    }//GEN-LAST:event_btn_showtimesMouseEntered

    private void btn_showtimesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showtimesMouseExited
        // TODO add your handling code here:
        btn_showtimes.setBackground(new Color(64,33,100));
    }//GEN-LAST:event_btn_showtimesMouseExited

    private void btn_revenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_revenueMouseClicked
        // TODO add your handling code here:
        new ManageRevenue(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_revenueMouseClicked

    private void btn_revenueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_revenueMouseEntered
        // TODO add your handling code here:
        btn_revenue.setBackground(new Color(37,12,65));
    }//GEN-LAST:event_btn_revenueMouseEntered

    private void btn_revenueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_revenueMouseExited
        // TODO add your handling code here:
        btn_revenue.setBackground(new Color(64,33,100));
    }//GEN-LAST:event_btn_revenueMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        new SignInView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setFont(new java.awt.Font("Segoe UI", 0, 14));
    }//GEN-LAST:event_logoutMouseExited
    public void showTable() {
        deftab.setRowCount(0);
        if(cboxAdmin.isSelected() && cboxCus.isSelected()){
            ArrayList<User> lstUsers = AdminController.getAllUsers();
            deftab.setRowCount(0);
            for(User s:lstUsers){
                System.out.println(s.getObject());
                deftab.addRow(s.getObject());
            
            }
        }
        if(cboxAdmin.isSelected()&&!cboxCus.isSelected()){
            ArrayList<Admin> lstUsers = AdminController.getAllAdmin();
            deftab.setRowCount(0);
            for(User s:lstUsers){
                System.out.println(s.getObject());
                deftab.addRow(s.getObject());
            
            }
        }
        if(!cboxAdmin.isSelected()&&cboxCus.isSelected()){
            ArrayList<Customer> lstUsers = AdminController.getAllCustormer();
            deftab.setRowCount(0);
            for(User s:lstUsers){
                System.out.println(s.getObject());
                deftab.addRow(s.getObject());
            
            }
        }
        if(!cboxAdmin.isSelected()&&!cboxCus.isSelected()){
            
            deftab.setRowCount(0);
            
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blank;
    private javax.swing.JPanel body;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnDel;
    private javax.swing.JLabel btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JPanel btn_accounts;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_films;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_max;
    private javax.swing.JPanel btn_min;
    private javax.swing.JPanel btn_revenue;
    private javax.swing.JPanel btn_showtimes;
    private javax.swing.JCheckBox cboxAdmin;
    private javax.swing.JCheckBox cboxCus;
    private javax.swing.JPanel checkboxAdmin;
    private javax.swing.JPanel checkboxCus;
    private javax.swing.JPanel crud;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header_bottom;
    private javax.swing.JPanel header_top;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_accounts;
    private javax.swing.JLabel lab_exit;
    private javax.swing.JLabel lab_films;
    private javax.swing.JLabel lab_home;
    private javax.swing.JLabel lab_max;
    private javax.swing.JLabel lab_min;
    private javax.swing.JLabel lab_revenue;
    private javax.swing.JLabel lab_showtimes;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel logout_pannel;
    private javax.swing.JPanel main_menu;
    private javax.swing.JPanel menu_btns;
    private javax.swing.JPanel menu_crud;
    private javax.swing.JPanel menu_main;
    private javax.swing.JPanel menu_search;
    private javax.swing.JPanel menu_top;
    private javax.swing.JPanel search;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JPanel type;
    // End of variables declaration//GEN-END:variables
}
