/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import Model.Customer;
import Controller.SignUpController;
/**
 *
 * @author ngnth
 */
public class SuccessfulSUView extends javax.swing.JFrame {

    /**
     * Creates new form SignUpView
     */
    public SuccessfulSUView() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        panel_right = new javax.swing.JPanel();
        jBut_SignIn = new javax.swing.JButton();
        jBut_SignUp1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_right.setBackground(new java.awt.Color(32, 33, 35));
        panel_right.setMaximumSize(new java.awt.Dimension(932, 820));
        panel_right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBut_SignIn.setBackground(new java.awt.Color(126, 87, 194));
        jBut_SignIn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jBut_SignIn.setForeground(new java.awt.Color(255, 255, 255));
        jBut_SignIn.setText("Sign In");
        jBut_SignIn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBut_SignIn.setBorderPainted(false);
        jBut_SignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBut_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_SignInActionPerformed(evt);
            }
        });
        panel_right.add(jBut_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 330, 40));
        jBut_SignIn.getAccessibleContext().setAccessibleName("JBut_SignUp");

        jBut_SignUp1.setBackground(new java.awt.Color(126, 87, 194));
        jBut_SignUp1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jBut_SignUp1.setForeground(new java.awt.Color(255, 255, 255));
        jBut_SignUp1.setText("Sign Up");
        jBut_SignUp1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBut_SignUp1.setBorderPainted(false);
        panel_right.add(jBut_SignUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 780, 330, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        panel_right.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Please sign in to continue...");
        panel_right.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 590, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Book Now, Go Anytime");
        panel_right.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 240, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Congratulation! You are our member now!");
        panel_right.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 590, 50));

        getContentPane().add(panel_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_SignInActionPerformed
        // TODO add your handling code here:
        new SignInView().setVisible(true);
    }//GEN-LAST:event_jBut_SignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuccessfulSUView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuccessfulSUView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuccessfulSUView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuccessfulSUView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuccessfulSUView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_SignIn;
    private javax.swing.JButton jBut_SignUp1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panel_right;
    // End of variables declaration//GEN-END:variables
}
